C4/Biblio.pm, C4/Items.pm
Optimizes embedding of item data in MARC and fixes several bottlenecks encountered while profiling OAI-PMH and exporting of records. There are three ways this is accomplished:
1.) Use state variables to hold prepared SQL statements so that the preparation is done only once.
2.) Create optimized method for fetching item fields for MARC embedding.
3.) Use the cache service more and where repeated calls are made.
Test plan:
1.) Before applying the patch, time an export_records.pl run for a set of biblios that also have items. Run it a couple of times to account for initial slowness and possible fluctuations. For example:
time misc/export_records.pl --record-type bibs --starting_biblionumber 960000 --ending_biblionumber 965000 --format xml --filename unoptimized.xml
2.) Apply the patch.
3.) …
=> Bug 20664: Optimize retrieval of biblio and item data

debian/templates/apache-shared-intranet.conf, debian/templates/apache-shared-opac.conf, etc/koha-httpd.conf
Some of the Javascript and CSS files with _ in their name won't load without these patches from the Koha community master branch.
=> KD-3225: Cherry-pick fixes from community master branch

Koha/Biblio.pm
There was deleted_on on both the main table and the joined table requiring disambiguation.
=> KD-3279: Fix REST API holdings endpoint

C4/Biblio.pm, C4/Holdings.pm, Koha/OAI/Server/Repository.pm
Include holdings fields in MARC records returned via OAI-PMH if include_items is enabled in oai conf file and SummaryHoldings is enabled in preferences.
=> KD-3280: Include holdings in OAI-PMH

circ/pendingreserves.pl
The "defined" check was left out incorrectly in the original
commit. This fixes following error:
[ERROR] Can't call method "reservesallowed" on an undefined value at
/home/koha/Koha/circ/pendingreserves.pl line 226.
=> Bug-2606: (squashable) Check if reservesallowed is defined before usage

circ/pendingreserves.pl
Without the curly braces the reservesallowed is treated as a method.
=> Bug-2606: (squashable) Add missing curly braces

circ/pendingreserves.pl
The Patron object needs to be accessed with method or otherwise the
value will be undef. We also should check if the issuing_rule is
defined instead of checking $issuing_rule->{reservesallowed} because
$issuing_rule->{reservesallowed} will always be undefined because
issuing_rule values need to be accessed with methods.
=> Bug-2606: (squashable) fix errors in check_issuingrules

misc/bin/koha-plack-daemon.sh, misc/plack/plack.psgi
This make it possible to use plack.psgi as a standalone Koha server and debug it without interrupting the normal Koha installation operations. Eg. have Apache2 not being able to forward to Plack.
=> Kd 0 parallel debugger

koha-tmpl/static_content/auth_examples/ajax_example.js.txt, koha-tmpl/static_content/auth_examples/ruby_example.rb.txt
Minttu from the NatLibFi was missing this.
Old REST API auth examples were forgotten.
This brings them back.
=> Bug 7174 - Authentication Rewrite - Resurrect auth examples

koha-tmpl/intranet-tmpl/prog/en/xslt/MARC21slim2intranetResults.xsl
Show sequental designation (362a) only after the full title, i.e. after
245a+245b+245n+245p. This way we don't split the title to two parts
where in the middle would be sequental designation information.
=> KD-2177: (squashable) Hakutulokseen 362a kenttä

C4/Reserves.pm
This prevents error happening because $issuing_rules->reservesallowed
would be undefined->reservesallowed in case there is no issuing rule.
=> KD-1939: (squashable) check if $issuing_rules variable is defined

C4/Matcher.pm
The commit b4392018bc1f9bf6a2f7dfe70b488856ad3a3897 (Bug 12478: make
things using SimpleSearch use the new version) removed the said
import. We still need it as C4::Search::new_record_from_zebra is called.
If you try to add a new record through records REST endpoint the error is visible. With Koha's own deduplicator (cgi-bin/koha/cataloguing/deduplicator.pl) the issue won't show up probably because some other code that is calling the get_matches function already has done the import.
=> Bug 12586: (follow-up) add missing C4::Search import

Makefile.PL, etc/koha-conf.xml, rewrite-config.PL
This makes it possible set custom mappings, index and field config
files for Elasticsearch with "make".
=> Make Elasticsearch settings configurable

Koha/Account/Line.pm, Koha/Biblio.pm, Koha/REST/V1/Checkout.pm, api/v1/swagger/definitions/biblio.json, api/v1/swagger/definitions/checkoutexpanded.json, t/db_dependent/Koha/Biblios.t, t/db_dependent/api/v1/biblios.t, t/db_dependent/api/v1/checkoutsexpanded.t
- Check patron blocks only once outside the loop
- Select all required records from the database with a join instead of requesting them separately
- Remove title_remainder for now since it needs the MARC record
- Check renewability only if patron does not have blocks
=> KD-3115: Improve performance of the checkouts/expanded API

misc/translator/text-extract.pl, misc/translator/text-extract2.pl, misc/translator/tmpl_process3.pl, misc/translator/translate, misc/translator/xgettext.pl
Perl 5.26 (or earlier) introduced a security feature, where implicitly
including the program directory as a Perl library directory no longer
happens (perl -I. ).
This causes translate to fail because it cannot find the *.pm -files in
it's own directory.
This patch adds the familiar mantra
use lib $FindBin::Bin;
to the relevant scripts.
To test:
1. Install Ubuntu18.04 or something else with Perl 5.26
2. Install Koha (we use the dev-install)
3. cd $KOHA_PATH/misc/translator/
4. perl translate create fi-FI
5. Observe problems with missing modules.
Signed-off-by: Julian Maurice <julian.maurice@biblibre.com>
Signed-off-by: Jonathan Druart <jonathan.druart@bugs.koha-community.org>
Cannot recreate the issue right now but the changes make sense.
=> Bug 21480: misc/translator/translate does not work with perl 5.26

Koha/Account/Line.pm
Although the code works, Perl gives a warning when comparing string
with a number:
[WARN] Argument "L 46217" isn't numeric in numeric eq (==) at
/home/koha/Koha/Koha/Account/Line.pm line 51.
This compares the two values as a string thus removing the warning.
=> Bug 15165: (squashable) remove Perl warning

C4/Circulation.pm
This cherry-picks commits from [bug 19487](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=19487). The higher education libraries are using the circulation rule "Refund lost item fee" set to "No" and it will create lost item fines that are related to an item that is already checked in and therefore leading to the error upon paying the fine as described in the community bug report.
=> Bug 19487: Fix internal server error when paying fines

Koha/REST/V1/Checkout.pm, api/v1/swagger/paths.json, api/v1/swagger/paths/checkouts.json, t/db_dependent/api/v1/checkouts.t
Adds endpoints v1/checkouts/paged and v1/checkouts/expanded/paged with parameters sort, order, offset and limit in addition to the ones supported by the normal v1/checkouts and v1/checkouts/expanded endpoints. Extends tests to cover these. Adds check for OpacRenewalAllowed preference to checkouts/expanded[/paged].
Needs review from someone else before committing.
=> KD-3511: REST API: Add support for sorting and paging checkouts

catalogue/showmarc.pl, koha-tmpl/intranet-tmpl/prog/en/modules/catalogue/detail.tt
Since there can be various fields that the user might want to quickly check, add a MARC preview button to the holdings list. Please feel free to rebase to bug 20447 if necessary.
=> KD-3593: Add MARC preview links to holdings list

Koha/Availability/Checks/IssuingRule.pm, Koha/Item/Availability/Hold.pm, t/db_dependent/Koha/Availability/Checks/IssuingRule.t
The previous commit didn't take into account whether reserves were allowed at all. This commit takes that into account so that the situation changes as follows:
Previously the condition was:
if there are items available for checkout and on shelf holds are allowed when xxxx
Now:
if there are items available for placing a hold and on shelf holds are allowed when xxxx
This new way in the commit is better in my opinion because we want to ignore those items that couldn't be put on hold anyway. If we don't do it this way then there can be a situation where some biblio cannot be reserved for example because there is a item available for only intra-day loan that nobody really wants to reserve because everybody wants the item that has 28 day loan period. So with this patch in-place we can now put …
=> KD-3721: (squashme) Fix missing check for on-shelf hold

Koha/REST/V1/Borrower.pm
This prevents REST logs going to SIP server logs and causing
permission issues if SIP server and REST server are run with different
users.
The code is duplicated from C4::SIP::ILS::Patron because the current
Koha-Suomi version doesn't have yet all the Koha::Patron accessors
available that are in the community version. In the future when
Koha-Suomi codebase is rebased we can get rid of most of the code and
simply use the Koha::Patron accessors.
This commit reveleas that, for example, too_many_items_charged is just a
static value '0', probably originally made to comply with an API of some
sort.
=> KD-3602: (squashable) do not depend on C4::SIP code

Koha/REST/V1/Borrower.pm
The variable $basic_privileges_ok was only set for the scope of the
for loop but it is supposed to be applied to the variable outside of
the loop.
=> KD-3602: (squashable) fix variable scope problem

misc/bin/koha-plack-daemon.sh
Follow-up to d727f47ae17db52fd7f4da7f74e78c4725428899
=> KD-0: Fix koha-plack-daemon.sh syntax error

C4/Installer.pm, installer/install_automatic.pl
Support default values from other languages
To test:
1. drop database koha; create database koha; exit;
2. perl installer/install_automatic.pl --lang fi-FI
3. Default values from installer/data/mysql/fi-FI should now be included
(take a look at patron categories, they should be in Finnish)
=> KD-1645 - Koha database autoinstaller and updater

Koha/REST/V1/Borrower.pm
I accidentally introduced this syntax error and it causes now warnings to logs. This removes the extra my statement
=> KD-3602: (squashable) fix syntax error by removing extra my statement

Koha/BiblioUtils.pm, Koha/MetadataRecord/Authority.pm, misc/search_tools/rebuild_elastic_search.pl
This pull request cherry-picks three patches from upstream required to minimally implement multiprocessing support for Elasticsearch indexing making it linearly faster based on the number of cores available on the system
=> Elasticsearch multiprocessing support

koha-tmpl/intranet-tmpl/prog/en/modules/members/memberentrygen.tt
This avoids Javascript injection problems that can happen for example
with bulk patron import tool in intranet.
=> Bug 14620: (follow-up) escape variables with html filter

Koha/Availability/Checks/Item.pm, Koha/Biblio/Availability/Hold.pm, Koha/Exceptions/Biblio.pm, Koha/Exceptions/Item.pm, Koha/Item.pm, Koha/Item/Availability/Hold.pm, Koha/Item/Availability/Search.pm, Koha/REST/V1/BiblioAvailability.pm, Koha/REST/V1/ItemAvailability.pm, api/v1/swagger/definitions/availability/reason.json, api/v1/swagger/paths/availability.json, t/db_dependent/Koha/Availability/Checks/Item.t, t/db_dependent/Koha/Biblio/Availability/Hold.t, t/db_dependent/Koha/Item/Availability/Hold/Opac/ItemStatus.t, t/db_dependent/Koha/Items.t, t/db_dependent/api/v1/availability.t
https://tiketti.koha-suomi.fi/issues/3375
=> Bug 23449: Get all available pickup locations from REST API

misc/cronjobs/iPostEPL/opuscapita_convert_and_send_print_notices.pl
Initialize the variable with empty string so it does not fill your
logs with «Use of uninitialized value $retstring in concatenation ...
at .../cronjobs/iPostEPL/opuscapita_convert_and_send_print_notices.pl
line 69» warnings.
=> KD-1892: (squashable) Fix uninitialized value

etc/logrotate.d/koha, misc/maintenance/anonymize_sip2_log.sh
This PR is a follow up to commit fcb8a12625b18455d171ac90c5d232cd96860b0d
Apparently there has been some issues with logrotate duplicating logfiles exponentially. Perhaps the issue is caused by too loosely defined paths. This PR aims to fix any remaining issues. Logrotate is a must to our production systems due to enormous log size growth (our sip2.log was 29GB:)
=> KD-2821: Logrotate improvements

Koha/Item/Availability/Search.pm
This reflects the reality as held items can be checked out. Only holds
that are in the waiting state (processed, pickup notification sent)
cannot be checked out.
=> KD-4059: Make unavailable only waiting holds

etc/logrotate.d/koha
Follow-up of https://github.com/KohaSuomi/Koha/pull/116
This commit fixes editx logs path for logrotate
Also removes useless / prefix from sip2 postrotate script path
=> KD-2821: (follow-up) Logrotate improvements

cataloguing/additem.pl
The i++ being in the for clause is sufficient because the $barcodeobj->next_value and C4::Barcodes::ValueBuilder::hbyyyyincr::get_barcode statements return a valid barcode always except when we are out of barcodes. 
Therefore, we can remove the other i++ statement inside the for a loop. In the case where we run out of barcodes, this adds the error "no_next_barcode" to the list of errors.
––-
The previous discussion was in PR https://github.com/KohaSuomi/Koha/pull/113
(also to refer related commits from IRC discussion: https://github.com/KohaSuomi/Koha/commit/8f1b7b88848fd9b0fc767e3ff7dcdc7a56f6ebff, https://github.com/KohaSuomi/kohasuomi/commit/ada6401c2c1e29bf4bb1a33e0153aa041ebac196 )
=> KD-4000: fix for KD-543 / 8f1b7b8 after which only half of the items became added,

installer/data/mysql/atomicupdate/KD-3816-Make-EDItX-use-vendor-edi-accounts.perl
Running exit() stopped the whole atomicupdate.pl script therefore the
atomicupdates coming after this one didn't run.
=> KD-3816: (squashable) Don't abort whole atomicupdate script

Koha/REST/V1/Borrower.pm
C4::SelfService is using an unblessed representation of Koha::Patron, however,
the REST API controller was not updated to match this change.
Toveri access control devices are broken without this commit. Please merge it into production branch.
=> KD-1159-5: Pass unblessed Koha::Patron from REST API to C4::SelfService

koha-tmpl/intranet-tmpl/prog/en/includes/member-main-address-style-de.inc, koha-tmpl/intranet-tmpl/prog/en/includes/member-main-address-style-fr.inc, koha-tmpl/intranet-tmpl/prog/en/includes/member-main-address-style-us.inc
This patch modifies the include files which contain the form fields for
city, state, zipcode, etc. shown on the patron entry screen. The files
are modified so that the city/state/zip <select> preselects a value
based on city, state, and zipcode matching the values in the
corresponding text fields.
To test, confirm that the bug's steps to reproduce are fixed:
- Enter two cities via Administration -> Patrons and circulation
-> Cities and towns:
Springfield, MA 01101
Springfield, VT 05156
- Edit a patron choosing, Springfield VT, and save.
- Edit the patron again and confirm that the correct city is
pre-selected.
- Confirm this result with all three different settings of the
"AddressFormat" system preference.
Signed-off-by: Amit Gupta <amit.gupta@informaticsglobal.com>
Signed-off-by: Nick …
=> Bug 15644 - (BACKPORTED) City dropdown default selection when modifying a patron matches only on city

Koha/SearchEngine/Elasticsearch.pm, Koha/SearchEngine/Elasticsearch/Indexer.pm, admin/searchengine/elasticsearch/mappings.yaml, misc/search_tools/rebuild_elastic_search.pl, t/Koha/SearchEngine/Elasticsearch.t
The first commit shows during indexing if there was an error with indexing a record, as previously it was a silent failure. The second one fixes indexing for records that have hundreds or more items in them.
=> Backport elasticsearch fixes

admin/searchengine/elasticsearch/mappings.yaml
The /cgi-bin/koha/catalogue/detail.pl page would not open because of
this error:
No mapping found for [local-number__sort.phrase] in order to sort on
This makes local-number search field sortable and fixes the issue.
=> KD-4229: Fix broken details page with Elasticsearch search engine

koha-tmpl/intranet-tmpl/prog/en/modules/acqui/tables/pendingorders_results.tt, svc/orders/search
Fix breakage by HTML-encoding the author name if the acq author
contained characters that broke the JSON.
Also fix JSON breakage if order had no lines attached.
Signed-off-by: Pasi Kallinen <pasi.kallinen@koha-suomi.fi>
=> KD-3172: Acquisition bugfix

Koha/Biblio/Availability/Hold.pm
If an item was unavailable only because item level holds were not
allowed then the item's pickup locations didn't appear in biblio level
hold pickup locations. This adds those missing pickup locations to
biblio level.
=> Bug 23449: (follow-up) Add missing biblio level pickup locations

Koha/REST/V1/Patron/Attribute.pm, api/v1/swagger/definitions.json, api/v1/swagger/definitions/patronattribute.json, api/v1/swagger/paths.json, api/v1/swagger/paths/patrons.json, t/db_dependent/api/v1/patronsattributes.t
two new REST API routes related to extended patron attributes
```
GET /patrons/attributes?code=attrkey&attribute=attrvalue
- list/search for patrons by extended patron attribute code and value
POST /patrons/attributes  {"code": "attrkey", "attribute": "attrvalue", "borrowernumber":100}
- add extended patron attribute for a patron
```
```prove t/db_dependent/api/v1/patronsattributes.t```
=> KD-4277: REST API support for extended patron attributes

misc/cronjobs/backup.sh
backup.sh can fail due to
```tar gzip of system logs failed```
this fixes the backup pipeline to not fail when log files change on disk during archival.
=> KD-0 Database backup script - Fix hot-archiving log files

C4/Reserves.pm, reserve/request.pl, t/db_dependent/Holds/DisallowHoldIfItemsAvailable.t
Few preparatory commits:
- check for defined "borrowerinfo" for not to run extra code
- "if" block optimization first to analyze already precomputed values
- and refactor to have separate subroutine "ItemsAnyAvailableForHold " in Reserves.pm + test update.
**Then that subroutine and test used in the last from the commits to make a fix:**
When "reserve/request.pl -> C4/Reserves.pm::IsAvailableForItemLevelRequest" called many times with hundred of items and "on shelf holds" parameter set to "If all unavailable" for these items + patron, it goes slow.
It happens because in subloop it is checking if all items available so it is O(n^2) and it re-checks each time the same info for each item with repeating DB/data requests.
Fix:
The inner loop 1:1 picked out into separate subroutine and called …
=> Bug 24185: Make holds page fast when 'on shelf holds' set to 'If all unavailable'

C4/Reserves.pm
If condition doesn't need last statement. The last statements were
probably added mistakenly because there was another while loop with
similar code where last statement is good to have for performance
reasons.
=> Bug 2520: (squashable) Fix syntax error

C4/SelfService/BlockManager.pm
The _isSthStale is not checking whether connection to DB is still
alive therefore producing errors such as
DBD::mysql::st execute failed: MySQL server has gone away
This removes the caching mechanishm in order to prevent such errors.
=> KD-4335: Remove broken DB connection caching

C4/Installer/PerlDependencies.pm, Koha/Cache.pm, koha-tmpl/intranet-tmpl/prog/en/modules/about.tt
When a high enough number of forks try to access for example system
preferences with Koha::Cache using memcached as backend the results of
different cache requests get mixed up.
The problem is fixed by using Cache::Memcached::Fast::Safe that is a
fork safe version of Cache::Memcached::Fast.
Sponsored-by: The National Library of Finland
Signed-off-by: David Cook <dcook@prosentient.com.au>
Works as described, and solves an insidious difficult to debug
problem in Koha.
=> Bug 13193: Make Memcached usage fork safe

Koha/REST/V1/Biblio.pm
The safe option only worked earlier for items even though it was meant
to disallow deletion of holdings records too.
=> KD-4302: (squashme) Don't delete holdings records with safe option

C4/Biblio.pm
ModZebra called with $record with items stripped in
ModBiblioMarc. Remove $record argument to force
record to be loaded again from database with items
embedded.
How to test:
1) Make sure biblios are indexed (with
rebuild_elastic_search.pl).
2) Perform a search that will produce a sample result
containing at least one biblio with items.
3) Edit and save a biblio with items.
4) Perform the same search again, the updated biblio
should now have no items when viewed in the search
results (No items).
5) Apply patch.
6) Repeat step 1-3.
7) The updated biblio should now have items when viewed
in the search results.
Signed-off-by: Josef Moravec <josef.moravec@gmail.com>
Signed-off-by: Kyle M Hall <kyle@bywatersolutions.com>
Signed-off-by: Nick Clemens <nick@bywatersolutions.com>
=> Bug 20535: ModZebra called with $record with items stripped

misc/cronjobs/holds/set_expirationdate_for_holds.pl
Holds made in Koha staff client don't automatically have
expiration date set (in Finna this date is set 2 years
into the future).
This patch adds new cronjob to set and update expiration
date 2 years from holds reserve date. Only holds without
expiration date are affected.
To test:
1. Have some holds without expiration date.
2. Run misc/cronjobs/holds/set_expirationdate_for_holds.pl -c
3. Confirm holds now have expiration date (2 years from reservation
date).
=> KD-4530: Cronjob for setting expirationdate for holds

koha-tmpl/intranet-tmpl/prog/en/modules/members/memberentrygen.tt
Adding 'password' to 'BorrowerUnwantedField' makes
unintended changes to patron form due missing
[% END %] tag on memberentrygen.tt.
To test:
1. Add 'password' to 'BorrowerUnwantedField'.
2. Edit patron, note after 'OPAC/Staff login' forms
structure is broken.
3. Apply this patch.
4. Confirm form is now displayed correctly.
=> KD-4641: Missing end tag on memberentrygen.tt

C4/OPLIB/OKM.pm
Retrieving reports leads to 'Internal server error' due changes
made how report tool handles and parses timeperiod.
=> KD-4724 (squashable): Fix timeperiod

C4/OPLIB/OKM.pm
Error handling for unmapped itemtype doesn't
work correctly due incorrect perl syntax.
=> KD-4724 (squashable): Fix error handling

C4/OPLIB/OKM.pm
Branchgroups begining with just two characters were ignored and
left out of statistics. Also generating statistics for all individual branches
didn't work due some outdated code.
=> KD 4724 (squashable): Fix branchcode handling

debian/scripts/koha-functions.sh, debian/scripts/koha-plack
in koha-plack-daemon
Since D10 start-stop-daemon changed its behaviour. From
start-stop-daemon manual:
"Warning: using this match option with a world-writable
pidfile or using it alone with a daemon that writes the
pidfile as an unprivileged (non-root) user will be refused
with an error (since version 1.19.3) as this is a security
risk, because either any user can write to it, or if the
daemon gets compromised, the contents of the pidfile
cannot be trusted, and then a privileged runner (such as
an init script executed as root) would end up acting on
any system process. Using /dev/null is exempt from these
checks."
This is fixed in community version with bug 25481.
=> KD-4838: Add --user when pidfile is used
