KohaSuomi/Koha

Koha/REST/V1/Checkout.pm
t/db_dependent/api/v1/checkoutshistory.t

Fixes tests too to not complain or die without an item type.

KD-3185: REST API: Add item and biblio fields to checkouts/history

---

Makefile.PL
etc/sru_server/catmandu.yml
etc/sru_server/config.yml
etc/sru_server/marcxml.tt
misc/bin/koha-sru-server.sh
misc/sru_server.pl

To test:
1. Make sure you have specified a working elasticsearch configuration in
koha-conf.xml and biblios index is populated with some data
2. Start SRU server by running "koha-dev/bin/koha-sru-server.sh start"
3. Try it out, for example: $ curl
"http://localhost:9998/sru?version=1.1&operation=searchRetrieve&query=dc.title=Test".
if you get back a bibliographic record all is good!

Bug 21210: Implement Elasticsearch based SRU server

---

etc/koha-conf.xml
koha-tmpl/intranet-tmpl/lib/hetula.0.0.1.min.js
koha-tmpl/intranet-tmpl/prog/en/js/hetula-service.js
koha-tmpl/intranet-tmpl/prog/en/js/ssn-service.js
koha-tmpl/intranet-tmpl/prog/en/modules/members/memberentrygen.tt
members/memberentry.pl

Configure the new $KOHA_CONF-variable 'hetula' to start using
Hetula - https://github.com/kivilahtio/Hetula
Requires no other action.
Uses Ecmascript 6 classes and Promises, which work on 2.5 years old Firefoxes and Chromes.
It is reasonable to expect the librarians browsers to be updated since then.

KD-1809 - Hetula-Koha integration

---

C4/Circulation.pm

See. 
https://tiketti.koha-suomi.fi:83/issues/3431

Bug 21512 - CalculateFinesOnReturn doesn't work without the syspref finesMode

---

Koha/Biblio.pm

Otherwise they can't actually be processed in Finna..

Bug 20447-1: Include suppressed holdings in REST API

---

C4/Installer/PerlDependencies.pm
misc/bin/koha-plack-daemon.sh
misc/plack/plack.psgi

Enable Remote debugging from the plack daemon.
Remains dormant until needed.

KD-0 - Plack remote debugging

---

Koha/Availability/ArticleRequest.pm
Koha/Availability/Checks/Biblioitem.pm
Koha/Availability/Checks/IssuingRule.pm
Koha/Availability/Checks/Patron.pm
Koha/Biblio/Availability/ArticleRequest.pm
Koha/Exceptions/ArticleRequest.pm
Koha/Item/Availability/ArticleRequest.pm
Koha/REST/V1/ArticleRequest.pm
Koha/REST/V1/Auth.pm
Koha/REST/V1/BiblioAvailability.pm
Koha/REST/V1/ItemAvailability.pm
api/v1/swagger/definitions.json
api/v1/swagger/definitions/articlerequest.json
api/v1/swagger/definitions/articlerequests.json
api/v1/swagger/definitions/articlerequeststatus.json
api/v1/swagger/parameters.json
api/v1/swagger/parameters/articlerequest.json
api/v1/swagger/paths.json
api/v1/swagger/paths/articlerequests.json
api/v1/swagger/paths/availability.json
api/v1/swagger/x-primitives.json
t/db_dependent/Koha/Availability/Checks/IssuingRule.t
t/db_dependent/api/v1/articlerequests.t

Modeled after holds functionality. This has been reviewed by kohaputti.

KD-3718: Add REST API support for article requests

---

Koha/Availability.pm
Koha/Availability/Checks.pm
Koha/REST/V1/Auth.pm
Koha/REST/V1/Records.pm
api/v1/swagger/definitions/holding.json
api/v1/swagger/definitions/item.json
api/v1/swagger/definitions/suggestion.json
t/db_dependent/Koha/Availability/Helpers.pm
t/db_dependent/api/v1/accountlines.t
t/db_dependent/api/v1/auth.t
t/db_dependent/api/v1/availability.t
t/db_dependent/api/v1/borrowers.t
t/db_dependent/api/v1/holds.t
t/db_dependent/api/v1/patrons.t
t/db_dependent/api/v1/payments.t
t/db_dependent/api/v1/records.t

This reverts commit ae959a39e2e4b350f8adb5e06944eee852ec40df, fixes a lot of issues with the tests and makes some of them more robust. Also removes Zebra dependency from the records endpoint tests.
To test: prove t/db_dependent/api/v1

KD-3739: Fix REST API tests and problems they uncovered

---

Makefile.PL
etc/log4perl.conf

After trying to automate the SRU server installation I noticed that a) it logged to wrong directory b) the SRU server was in the Makefile.PL so it didn't get copied to the bin directory.

Couple fixes for SRU server

---

installer/onboarding.pl

Unable to finish web installer's onboarding tool because adding a superlibrarian fails due to
permission refactor in Bug 14540.

Bug 14540: (Koha-Suomi follow-up) Fix onboarding tool permission issues

---

Koha/REST/V1/Hold.pm
api/v1/swagger/paths/holds.json

With this change people reserving items can add additional notes about the reserve if they wish

KD-4048: Add ability to add reservenotes to holds endpoint

---

installer/data/mysql/fi-FI/marcflavour/marc21/mandatory/marc21_framework_DEFAULT.sql

Bug 22471: Add Finnish MARC21 subfield structure - Followup 1

---

Koha/REST/V1/Biblio.pm
api/v1/swagger/paths.json
api/v1/swagger/paths/biblios.json
t/db_dependent/api/v1/biblios.t

Adds a non-hierarchical endpoint for fetching serial subsciptions. Includes all the location information and other information to be displayed to a patron.

KD-4167: Add REST API endpoint for serial subscriptions

---

Koha/REST/V1/Item.pm
api/v1/swagger/parameters.json
api/v1/swagger/parameters/item.json
api/v1/swagger/paths.json
api/v1/swagger/paths/items.json
api/v1/swagger/x-primitives.json

This adds the ability to list items based on given barcodes.

KD-4177: Add REST API support for listing items

---

koha-tmpl/intranet-tmpl/prog/en/modules/tools/sendOverdueBills.tt

See c35a49144fc958fafa111f1372f70d0e5aa525c1
Just adds the same functionality to another link as here:
https://github.com/KohaSuomi/Koha/commit/c35a49144fc958fafa111f1372f70d0e5aa525c1#diff-07d79c86d682827b2ed2e3d6c534c74bR141

KD-1902: (squashable) Add basepath to example link

---

Koha/Patron/Message.pm
Koha/REST/V1/Auth.pm
Koha/REST/V1/Messages.pm
api/v1/swagger/definitions.json
api/v1/swagger/definitions/message.json
api/v1/swagger/parameters.json
api/v1/swagger/parameters/message.json
api/v1/swagger/paths.json
api/v1/swagger/paths/messages.json
api/v1/swagger/x-primitives.json
t/db_dependent/Koha/Patron/Messages.t
t/db_dependent/api/v1/messages.t

https://tiketti.koha-suomi.fi/issues/4222
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=23998
Bug 23998 depends on Bug 24016.
To test:
1. prove t/db_dependent/Koha/Patron/Messages.t
2. prove t/db_dependent/api/v1/messages.t

Bug 23998: Messages REST API

---

etc/zebradb/etc/word-phrase-utf.chr

Adds transliteration for some characters to make it easier to search
for Sami language records.
See community bug 24063
Signed-off-by: Pasi Kallinen <pasi.kallinen@koha-suomi.fi>

KD-3544: Add Sami language characters to Zebra

---

koha-tmpl/intranet-tmpl/prog/en/xslt/MARC21slim2intranetDetail.xsl
koha-tmpl/opac-tmpl/bootstrap/en/xslt/MARC21slim2OPACDetail.xsl

Bug 24322: National Library of Medicine (NLM) call number to XSLT Detail

---

C4/Reserves.pm

Signed-off-by: Hans Palsson <hans.palsson@hkr.se>
Signed-off-by: Kyle M Hall <kyle@bywatersolutions.com>

Bug 20567: Count found holds for holds limit

---

admin/searchengine/elasticsearch/mappings.yaml

This includes all the clear requests for search fields I found from the wiki page https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Indeksointitarpeet. Some of the requests could be for holdings record or biblio record so I have to ask more clarifications for the remaining search fields that are wanted. This pull request should however be ready to be merged.

KD-3883: Add search fields used by Finnish libraries

---

koha-tmpl/intranet-tmpl/prog/en/modules/acqui/tables/pendingorders_results.tt

This escapes special characters correctly.

KD-4336: Use HTML filter in acquisition module's template

---

C4/Calendar.pm
t/db_dependent/Holidays.t

Related to: https://tiketti.koha-suomi.fi/issues/4338

Bug 19475: Calendar copy creates duplicates

---

Koha/MessageQueue/PrintProviderInterface.pm

If cronjob overduemessages.pl doesn't find item to charge
while generating links for accountlines notes, process to
add fines for patrons fails. This patch adds code to check if
item is found (if not, no note is added) and prints line with
unfoundable items itemnumber to cronjobs log file.
There was also issue with cronjob  generating unusable links.
This was due item found from resultset returning hash references
instead of biblionumber. Using Koha::Items instead bypasses this.
Finally in order to prevent  DBIx::Class::Storage::DBI warnings
flooding log file we have to search letter templates language.

KD-4367: Overduemessages.pl fails to add fines

---

C4/Barcodes/ValueBuilder.pm
Koha/Procurement/OrderProcessor.pm

To prevent duplicate barcodes generating, fetch changing
value to the end of barcode from sequences table.

KD-4792 (squashable): Prevent duplicate barcodes
